version: '3'

services:
# FRONT END
  # front:
  #   image: node:16
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 3001:3000
  #   command: yarn dev:front


  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src/client/dist:/usr/share/nginx/html

  client:
    image: node:16
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:5173
    command: yarn dev:client

  sb:
    image: node:14
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "6006:6006"
    command: yarn storybook