/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace BasePool {
  export type PoolInfoStruct = {
    spotPrice: PromiseOrValue<BigNumberish>;
    delta: PromiseOrValue<BigNumberish>;
    spread: PromiseOrValue<BigNumberish>;
    buyNum: PromiseOrValue<BigNumberish>;
    sellNum: PromiseOrValue<BigNumberish>;
  };

  export type PoolInfoStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    spotPrice: BigNumber;
    delta: BigNumber;
    spread: BigNumber;
    buyNum: BigNumber;
    sellNum: BigNumber;
  };

  export type UserInfoStruct = {
    initBuyNum: PromiseOrValue<BigNumberish>;
    initSellNum: PromiseOrValue<BigNumberish>;
    initSellAmount: PromiseOrValue<BigNumberish>;
    totalNFTpoint: PromiseOrValue<BigNumberish>;
    totalFTpoint: PromiseOrValue<BigNumberish>;
  };

  export type UserInfoStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    initBuyNum: BigNumber;
    initSellNum: BigNumber;
    initSellAmount: BigNumber;
    totalNFTpoint: BigNumber;
    totalFTpoint: BigNumber;
  };
}

export interface Pool721Interface extends utils.Interface {
  functions: {
    "bondingCurve()": FunctionFragment;
    "buyEventNum()": FunctionFragment;
    "collection()": FunctionFragment;
    "getAllHoldIds()": FunctionFragment;
    "getCalcBuyInfo(uint256,uint256)": FunctionFragment;
    "getCalcSellInfo(uint256,uint256)": FunctionFragment;
    "getPoolInfo()": FunctionFragment;
    "getUserInfo(address)": FunctionFragment;
    "getUserStakeFTfee(address)": FunctionFragment;
    "getUserStakeNFTfee(address)": FunctionFragment;
    "holdIds(uint256)": FunctionFragment;
    "isOtherStake()": FunctionFragment;
    "isPair()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "paymentToken()": FunctionFragment;
    "poolInfo()": FunctionFragment;
    "protocolFeeRatio()": FunctionFragment;
    "router()": FunctionFragment;
    "sellEventNum()": FunctionFragment;
    "setProtocolFeeRatio(uint256)": FunctionFragment;
    "setRouter(address)": FunctionFragment;
    "stakeFT(uint256,address)": FunctionFragment;
    "stakeFTprice()": FunctionFragment;
    "stakeNFT(uint256[],address)": FunctionFragment;
    "stakeNFTprice()": FunctionFragment;
    "swapFTforNFT(uint256[],address)": FunctionFragment;
    "swapNFTforFT(uint256[],uint256,address)": FunctionFragment;
    "totalFTfee()": FunctionFragment;
    "totalFTpoint()": FunctionFragment;
    "totalNFTfee()": FunctionFragment;
    "totalNFTpoint()": FunctionFragment;
    "withdrawFT(uint256,uint256[],address)": FunctionFragment;
    "withdrawFee(address)": FunctionFragment;
    "withdrawNFT(uint256[],address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bondingCurve"
      | "buyEventNum"
      | "collection"
      | "getAllHoldIds"
      | "getCalcBuyInfo"
      | "getCalcSellInfo"
      | "getPoolInfo"
      | "getUserInfo"
      | "getUserStakeFTfee"
      | "getUserStakeNFTfee"
      | "holdIds"
      | "isOtherStake"
      | "isPair"
      | "onERC721Received"
      | "owner"
      | "paymentToken"
      | "poolInfo"
      | "protocolFeeRatio"
      | "router"
      | "sellEventNum"
      | "setProtocolFeeRatio"
      | "setRouter"
      | "stakeFT"
      | "stakeFTprice"
      | "stakeNFT"
      | "stakeNFTprice"
      | "swapFTforNFT"
      | "swapNFTforFT"
      | "totalFTfee"
      | "totalFTpoint"
      | "totalNFTfee"
      | "totalNFTpoint"
      | "withdrawFT"
      | "withdrawFee"
      | "withdrawNFT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bondingCurve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyEventNum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllHoldIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCalcBuyInfo",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCalcSellInfo",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakeFTfee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStakeNFTfee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "holdIds",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isOtherStake",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPair", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "poolInfo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sellEventNum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeRatio",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRouter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeFT",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeFTprice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakeNFT",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeNFTprice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapFTforNFT",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "swapNFTforFT",
    values: [
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFTfee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFTpoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalNFTfee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalNFTpoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFT",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNFT",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "bondingCurve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyEventNum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "collection", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllHoldIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCalcBuyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCalcSellInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakeFTfee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStakeNFTfee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "holdIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isOtherStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellEventNum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakeFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeFTprice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeNFTprice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapFTforNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapNFTforFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalFTfee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFTpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalNFTfee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalNFTpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdrawFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNFT",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Pool721 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Pool721Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bondingCurve(overrides?: CallOverrides): Promise<[string]>;

    buyEventNum(overrides?: CallOverrides): Promise<[BigNumber]>;

    collection(overrides?: CallOverrides): Promise<[string]>;

    getAllHoldIds(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getCalcBuyInfo(
      _itemNum: PromiseOrValue<BigNumberish>,
      _spotPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCalcSellInfo(
      _itemNum: PromiseOrValue<BigNumberish>,
      _spotPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPoolInfo(
      overrides?: CallOverrides
    ): Promise<[BasePool.PoolInfoStructOutput]>;

    getUserInfo(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BasePool.UserInfoStructOutput]>;

    getUserStakeFTfee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _userFee: BigNumber }>;

    getUserStakeNFTfee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _userFee: BigNumber }>;

    holdIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isOtherStake(overrides?: CallOverrides): Promise<[boolean]>;

    isPair(overrides?: CallOverrides): Promise<[boolean]>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paymentToken(overrides?: CallOverrides): Promise<[string]>;

    poolInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        spotPrice: BigNumber;
        delta: BigNumber;
        spread: BigNumber;
        buyNum: BigNumber;
        sellNum: BigNumber;
      }
    >;

    protocolFeeRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    router(overrides?: CallOverrides): Promise<[string]>;

    sellEventNum(overrides?: CallOverrides): Promise<[BigNumber]>;

    setProtocolFeeRatio(
      _newProtocolFeeRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRouter(
      _newRouter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stakeFT(
      _itemNum: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stakeFTprice(overrides?: CallOverrides): Promise<[BigNumber]>;

    stakeNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stakeNFTprice(overrides?: CallOverrides): Promise<[BigNumber]>;

    swapFTforNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapNFTforFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _minExpectFee: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    totalFTfee(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalFTpoint(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalNFTfee(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalNFTpoint(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawFT(
      _userSellNum: PromiseOrValue<BigNumberish>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFee(
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  bondingCurve(overrides?: CallOverrides): Promise<string>;

  buyEventNum(overrides?: CallOverrides): Promise<BigNumber>;

  collection(overrides?: CallOverrides): Promise<string>;

  getAllHoldIds(overrides?: CallOverrides): Promise<BigNumber[]>;

  getCalcBuyInfo(
    _itemNum: PromiseOrValue<BigNumberish>,
    _spotPrice: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCalcSellInfo(
    _itemNum: PromiseOrValue<BigNumberish>,
    _spotPrice: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPoolInfo(
    overrides?: CallOverrides
  ): Promise<BasePool.PoolInfoStructOutput>;

  getUserInfo(
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BasePool.UserInfoStructOutput>;

  getUserStakeFTfee(
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUserStakeNFTfee(
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  holdIds(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isOtherStake(overrides?: CallOverrides): Promise<boolean>;

  isPair(overrides?: CallOverrides): Promise<boolean>;

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  paymentToken(overrides?: CallOverrides): Promise<string>;

  poolInfo(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      spotPrice: BigNumber;
      delta: BigNumber;
      spread: BigNumber;
      buyNum: BigNumber;
      sellNum: BigNumber;
    }
  >;

  protocolFeeRatio(overrides?: CallOverrides): Promise<BigNumber>;

  router(overrides?: CallOverrides): Promise<string>;

  sellEventNum(overrides?: CallOverrides): Promise<BigNumber>;

  setProtocolFeeRatio(
    _newProtocolFeeRatio: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRouter(
    _newRouter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stakeFT(
    _itemNum: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stakeFTprice(overrides?: CallOverrides): Promise<BigNumber>;

  stakeNFT(
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _user: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stakeNFTprice(overrides?: CallOverrides): Promise<BigNumber>;

  swapFTforNFT(
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _user: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapNFTforFT(
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _minExpectFee: PromiseOrValue<BigNumberish>,
    _user: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  totalFTfee(overrides?: CallOverrides): Promise<BigNumber>;

  totalFTpoint(overrides?: CallOverrides): Promise<BigNumber>;

  totalNFTfee(overrides?: CallOverrides): Promise<BigNumber>;

  totalNFTpoint(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawFT(
    _userSellNum: PromiseOrValue<BigNumberish>,
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _user: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFee(
    _user: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawNFT(
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _user: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bondingCurve(overrides?: CallOverrides): Promise<string>;

    buyEventNum(overrides?: CallOverrides): Promise<BigNumber>;

    collection(overrides?: CallOverrides): Promise<string>;

    getAllHoldIds(overrides?: CallOverrides): Promise<BigNumber[]>;

    getCalcBuyInfo(
      _itemNum: PromiseOrValue<BigNumberish>,
      _spotPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCalcSellInfo(
      _itemNum: PromiseOrValue<BigNumberish>,
      _spotPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPoolInfo(
      overrides?: CallOverrides
    ): Promise<BasePool.PoolInfoStructOutput>;

    getUserInfo(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BasePool.UserInfoStructOutput>;

    getUserStakeFTfee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserStakeNFTfee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    holdIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOtherStake(overrides?: CallOverrides): Promise<boolean>;

    isPair(overrides?: CallOverrides): Promise<boolean>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    paymentToken(overrides?: CallOverrides): Promise<string>;

    poolInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        spotPrice: BigNumber;
        delta: BigNumber;
        spread: BigNumber;
        buyNum: BigNumber;
        sellNum: BigNumber;
      }
    >;

    protocolFeeRatio(overrides?: CallOverrides): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<string>;

    sellEventNum(overrides?: CallOverrides): Promise<BigNumber>;

    setProtocolFeeRatio(
      _newProtocolFeeRatio: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRouter(
      _newRouter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    stakeFT(
      _itemNum: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    stakeFTprice(overrides?: CallOverrides): Promise<BigNumber>;

    stakeNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    stakeNFTprice(overrides?: CallOverrides): Promise<BigNumber>;

    swapFTforNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapNFTforFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _minExpectFee: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalFTfee(overrides?: CallOverrides): Promise<BigNumber>;

    totalFTpoint(overrides?: CallOverrides): Promise<BigNumber>;

    totalNFTfee(overrides?: CallOverrides): Promise<BigNumber>;

    totalNFTpoint(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawFT(
      _userSellNum: PromiseOrValue<BigNumberish>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    bondingCurve(overrides?: CallOverrides): Promise<BigNumber>;

    buyEventNum(overrides?: CallOverrides): Promise<BigNumber>;

    collection(overrides?: CallOverrides): Promise<BigNumber>;

    getAllHoldIds(overrides?: CallOverrides): Promise<BigNumber>;

    getCalcBuyInfo(
      _itemNum: PromiseOrValue<BigNumberish>,
      _spotPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCalcSellInfo(
      _itemNum: PromiseOrValue<BigNumberish>,
      _spotPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPoolInfo(overrides?: CallOverrides): Promise<BigNumber>;

    getUserInfo(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserStakeFTfee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserStakeNFTfee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    holdIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOtherStake(overrides?: CallOverrides): Promise<BigNumber>;

    isPair(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paymentToken(overrides?: CallOverrides): Promise<BigNumber>;

    poolInfo(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeRatio(overrides?: CallOverrides): Promise<BigNumber>;

    router(overrides?: CallOverrides): Promise<BigNumber>;

    sellEventNum(overrides?: CallOverrides): Promise<BigNumber>;

    setProtocolFeeRatio(
      _newProtocolFeeRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRouter(
      _newRouter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stakeFT(
      _itemNum: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stakeFTprice(overrides?: CallOverrides): Promise<BigNumber>;

    stakeNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stakeNFTprice(overrides?: CallOverrides): Promise<BigNumber>;

    swapFTforNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapNFTforFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _minExpectFee: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    totalFTfee(overrides?: CallOverrides): Promise<BigNumber>;

    totalFTpoint(overrides?: CallOverrides): Promise<BigNumber>;

    totalNFTfee(overrides?: CallOverrides): Promise<BigNumber>;

    totalNFTpoint(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawFT(
      _userSellNum: PromiseOrValue<BigNumberish>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFee(
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bondingCurve(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyEventNum(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collection(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllHoldIds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCalcBuyInfo(
      _itemNum: PromiseOrValue<BigNumberish>,
      _spotPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCalcSellInfo(
      _itemNum: PromiseOrValue<BigNumberish>,
      _spotPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPoolInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserInfo(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserStakeFTfee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserStakeNFTfee(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    holdIds(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOtherStake(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isPair(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paymentToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeRatio(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    router(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sellEventNum(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setProtocolFeeRatio(
      _newProtocolFeeRatio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRouter(
      _newRouter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stakeFT(
      _itemNum: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stakeFTprice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stakeNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stakeNFTprice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapFTforNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapNFTforFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _minExpectFee: PromiseOrValue<BigNumberish>,
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    totalFTfee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalFTpoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalNFTfee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalNFTpoint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawFT(
      _userSellNum: PromiseOrValue<BigNumberish>,
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFee(
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawNFT(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _user: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
